### ISSUE TITLE
just in case...

### ISSUE THREAD

**Issue by v1k0d3n** [jainvipin/ubuntu-kubernetes-install#1]
ran across this page actually looking for something entirely different, but in trying to help it looks like google changed the name of the .md. they're pointing at: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md now (or at least i think?).

anyway, just wanted to help out. have a happy new year! :+1: 

v1k

**Comment by jainvipin** [comment]
@v1k0d3n - thanks!

New year wishes!

Will update to point to the new links... Meanwhile we (@contiv) are leveraging ansible to do cluster-wide installation of k8s on arbitrary set of vms/bare-metals, in case anyone is looking for that I could point that that too... and then close the issue.

**Comment by v1k0d3n** [comment]
i am interested in that. i started to use the kubernetes/contrib/ansible, but it seems broken in a few ways. i was able to bypass the vagrant > openstack buildout with a terraform IaaS openstack pre-deployment, and then I ran the ansible setup afterwards which works for flannel. i'm actually looking for a way to use opencontrail in place of flannel...which led me to this page very, very indirectly! haha

here's the repos i was referring to:
initial ansible (in contrib): https://github.com/kubernetes/contrib/tree/master/ansible
my terraform added rather than using vagrant: https://github.com/v1k0d3n/terransikube

i am in the process of learning ansible...hopefully i can learn to correct some of these playbooks on my own after some time working with them.

**Comment by jainvipin** [comment]
@v1k0d3n - here at Contiv we (@contiv) were able to bring up k8s cluster with contrib and setup k8s ok with some changes to contrib (see the steps to bring it on your own). 
https://github.com/contiv/netplugin/tree/master/mgmtfn/k8splugin

You might be better off taking the above, replace contiv if you don't intend on using it with something else...

**Comment by jainvipin** [comment]
Also updated the README to point to correct reference:
http://kubernetes.io/v1.1/docs/getting-started-guides/ubuntu.html

**Comment by jainvipin** [comment]
@v1k0d3n - ping back if you are good with setting up a ubuntu cluster on your own.
Feel free to close the issue if above hints have helped or something else that you'd like to note here.

**Comment by v1k0d3n** [comment]
@jainvipin thank you! I think I'm good now. I ended up modifying some of the contrib after a lot of work with Juniper to get the Opencontrail bits working as well. Now It's working with a base installation of Ubuntu for both Flannel and Opencontrail (like what I think you're doing), but it also works for CentOS and Fedora for Flannel...and I am working on repairing some of the contrib work to get Opencontrail working for those as well. I plan on cleaning this up a bit, because it was put together pretty quickly with just single playbooks, but I plan on making this a lot better soon...

Here's the link: https://github.com/v1k0d3n/fansikube

Thanks for your updates and replies!

**Comment by jainvipin** [comment]
ok awesome, will check out your link!! I will close this issue.
of course, contiv work will be upstreamed to contrib as well, and works with centos.
